from datetime import datetime, timedelta, timezone

import pytest
from pydantic import ValidationError

from services.contracts import (
    ArtifactMetadataV1,
    ExecutionAttemptV1,
    NormalizedRequestV1,
    PlanV1,
    RetentionPolicyV1,
    RouteDecisionV1,
    TaskStateV1,
    ToolSpecV1,
)


NOW = datetime(2026, 7, 14, 17, 0, tzinfo=timezone.utc)
SHA256 = "a" * 64


def normalized_request(**overrides):
    values = {
        "request_id": "req-001",
        "user_message": "Inspect the repository and report the result.",
        "attachments": [],
        "source": "api",
        "project_hint": r"C:\work\project",
        "explicit_route": None,
        "created_at": NOW,
        "correlation_id": "corr-001",
    }
    values.update(overrides)
    return NormalizedRequestV1(**values)


def artifact(**overrides):
    values = {
        "artifact_id": "artifact-001",
        "type": "report",
        "path": "outputs/report.md",
        "hash": SHA256,
        "producer": "qwen_code",
        "source_request": "req-001",
        "created_at": NOW,
        "provenance": ["generated by task task-001"],
        "retention": RetentionPolicyV1(policy="task", expires_at=None),
    }
    values.update(overrides)
    return ArtifactMetadataV1(**values)


def task_state(**overrides):
    values = {
        "task_id": "task-001",
        "request_id": "req-001",
        "status": "running",
        "attempts": 1,
        "executor": "qwen_code",
        "project": r"C:\work\project",
        "worktree": r"C:\work\project",
        "artifacts": [],
        "modified_files": [],
        "unresolved_errors": [],
        "next_action": "Run the verification suite.",
        "created_at": NOW,
        "updated_at": NOW,
    }
    values.update(overrides)
    return TaskStateV1(**values)


def test_normalized_request_validates_and_round_trips_as_version_1():
    request = normalized_request()
    restored = NormalizedRequestV1.model_validate_json(request.model_dump_json())

    assert restored == request
    assert restored.schema_version == "1.0"
    assert restored.created_at.utcoffset() == timedelta(0)


def test_stage002_optional_fields_keep_old_v1_payloads_compatible():
    legacy_request = normalized_request().model_dump()
    for field in ("routing_override", "override_conflict", "project_resolution"):
        legacy_request.pop(field, None)
    restored = NormalizedRequestV1.model_validate(legacy_request)

    assert restored.routing_override is None
    assert restored.override_conflict is False
    assert restored.project_resolution is None


@pytest.mark.parametrize(
    "overrides",
    [
        {"user_message": "   "},
        {"created_at": datetime(2026, 7, 14, 17, 0)},
        {"explicit_route": "unknown"},
    ],
)
def test_normalized_request_rejects_invalid_required_values(overrides):
    with pytest.raises(ValidationError):
        normalized_request(**overrides)


def test_internal_contracts_reject_unknown_fields():
    with pytest.raises(ValidationError):
        NormalizedRequestV1(
            **normalized_request().model_dump(),
            undocumented_extension=True,
        )


def test_attachment_rejects_inline_data_url_and_content_field():
    inline = {
        "attachment_id": "attachment-001",
        "kind": "image",
        "reference": "data:image/png;base64,AAAA",
        "media_type": "image/png",
        "size_bytes": 4,
        "sha256": SHA256,
        "provenance": [],
    }
    with pytest.raises(ValidationError):
        normalized_request(attachments=[inline])

    inline["reference"] = "inbox/image.png"
    inline["content"] = "AAAA"
    with pytest.raises(ValidationError):
        normalized_request(attachments=[inline])


def test_route_decision_accepts_current_local_code_boundary():
    decision = RouteDecisionV1(
        request_id="req-001",
        route="local_code",
        executor="qwen_code",
        model="local-strong",
        profile="coding",
        reason_codes=["repository.mutation"],
        risk="medium",
        fallback={
            "route": "codex_bundle",
            "executor": "codex_bundle",
            "reason_codes": ["local.failure"],
        },
        project=r"C:\work\project",
        required_locks=["qwen_agent", "gpu_heavy", "worktree:project-001"],
    )

    assert decision.schema_version == "1.0"
    assert decision.route == "local_code"
    assert decision.executor == "qwen_code"


@pytest.mark.parametrize(
    "changes",
    [
        {"reason_codes": []},
        {"executor": "playwright"},
        {"risk": "unknown"},
        {"required_locks": ["gpu_heavy", "gpu_heavy"]},
    ],
)
def test_route_decision_rejects_invalid_contracts(changes):
    values = {
        "request_id": "req-001",
        "route": "local_code",
        "executor": "qwen_code",
        "model": "local-strong",
        "profile": "coding",
        "reason_codes": ["repository.mutation"],
        "risk": "medium",
        "fallback": None,
        "project": r"C:\work\project",
        "required_locks": ["qwen_agent", "gpu_heavy"],
    }
    values.update(changes)
    with pytest.raises(ValidationError):
        RouteDecisionV1(**values)


def test_route_decision_rejects_incompatible_fallback_executor():
    with pytest.raises(ValidationError, match="incompatible"):
        RouteDecisionV1(
            request_id="req-001",
            route="local_code",
            executor="qwen_code",
            model="local-strong",
            profile="coding",
            reason_codes=["repository.mutation"],
            risk="medium",
            fallback={
                "route": "image",
                "executor": "qwen_code",
                "reason_codes": ["local.failure"],
            },
            project=r"C:\work\project",
            required_locks=["qwen_agent", "gpu_heavy"],
        )


def test_task_state_accepts_running_complete_and_failed_states():
    running = task_state()
    complete = task_state(
        status="complete",
        artifacts=[artifact()],
        modified_files=["services/example.py"],
        next_action=None,
        updated_at=NOW + timedelta(seconds=10),
    )
    failed = task_state(
        status="failed",
        unresolved_errors=["test suite returned exit code 1"],
        next_action="Inspect the failing test.",
        updated_at=NOW + timedelta(seconds=20),
    )

    assert running.status == "running"
    assert complete.status == "complete"
    assert failed.status == "failed"


def test_execution_attempt_requires_bounded_terminal_failure_evidence():
    attempt = ExecutionAttemptV1(
        index=1,
        executor="qwen_code",
        model="local-strong",
        outcome="failed",
        reason_codes=["executor.local_failure"],
        command_summaries=["qwen_code bounded invocation"],
        error_summary="pytest returned exit code 1",
        modified_files=["services/app.py"],
        artifact_refs=["outputs/pytest.log"],
        started_at=NOW,
        finished_at=NOW + timedelta(seconds=2),
    )

    assert attempt.outcome == "failed"
    with pytest.raises(ValidationError):
        ExecutionAttemptV1(
            **{**attempt.model_dump(), "error_summary": None}
        )


@pytest.mark.parametrize(
    "changes",
    [
        {"attempts": -1},
        {"status": "failed", "unresolved_errors": []},
        {"status": "complete", "unresolved_errors": ["still broken"]},
        {"updated_at": NOW - timedelta(seconds=1)},
        {"modified_files": ["data:text/plain,inline"]},
    ],
)
def test_task_state_rejects_invalid_states(changes):
    with pytest.raises(ValidationError):
        task_state(**changes)


def test_artifact_rejects_invalid_hash_and_inline_path():
    with pytest.raises(ValidationError):
        artifact(hash="not-a-sha256")
    with pytest.raises(ValidationError):
        artifact(path="data:application/octet-stream;base64,AAAA")


def test_plan_and_tool_spec_cover_the_remaining_required_contracts():
    plan = PlanV1(
        goal="Inspect the project and produce a verified report.",
        subtasks=["Inspect tracked source files.", "Run bounded verification."],
        tools=["filesystem", "pytest"],
        acceptance_criteria=["The report cites concrete evidence."],
        risk="low",
        approvals=[],
        verification_plan=["Run the targeted tests."],
        context_budget={
            "max_input_tokens": 32_768,
            "reserved_output_tokens": 4_096,
            "max_attachment_bytes": 10_000_000,
        },
    )
    tool = ToolSpecV1(
        name="playwright.inspect",
        version="1.0",
        input_schema={"type": "object", "properties": {"url": {"type": "string"}}},
        output_schema={"type": "object", "properties": {"title": {"type": "string"}}},
        health={
            "kind": "command",
            "target": "services/browser/health.mjs",
            "timeout_seconds": 30,
        },
        permissions=["network.read"],
        risk="medium",
        timeout_seconds=120,
        retry={"max_attempts": 2, "backoff_seconds": 1, "retryable_errors": ["timeout"]},
        availability="available",
        locality="local",
    )

    assert plan.schema_version == "1.0"
    assert tool.schema_version == "1.0"


@pytest.mark.parametrize(
    "input_schema",
    [
        {"default": "data:image/png;base64,AAAA"},
        {"default": b"binary"},
    ],
)
def test_tool_spec_rejects_inline_payloads_in_json_schema(input_schema):
    with pytest.raises(ValidationError):
        ToolSpecV1(
            name="unsafe.tool",
            version="1.0",
            input_schema=input_schema,
            output_schema={"type": "object"},
            health={"kind": "none", "target": None, "timeout_seconds": 1},
            permissions=[],
            risk="low",
            timeout_seconds=1,
            retry={"max_attempts": 1, "backoff_seconds": 0, "retryable_errors": []},
            availability="disabled",
            locality="local",
        )


def test_pydantic_json_schema_is_versioned_machine_source():
    schema = NormalizedRequestV1.model_json_schema()

    assert schema["properties"]["schema_version"]["const"] == "1.0"
    assert {
        "request_id",
        "user_message",
        "attachments",
        "source",
        "project_hint",
        "explicit_route",
        "created_at",
        "correlation_id",
    }.issubset(schema["required"])
