"""Versioned internal contracts for Locestra.

The Pydantic models are the machine-readable source of truth.  Consumers that
persist or exchange a contract must retain ``schema_version`` and import the
matching versioned model explicitly.
"""

from services.contracts.v1 import (
    CONTRACT_VERSION,
    ActionKind,
    ArtifactMetadataV1,
    AttachmentRefV1,
    AttachmentKind,
    AttemptOutcome,
    AvailabilityStatus,
    ComplexityLevel,
    ContextBudgetV1,
    DecisionStatus,
    ExecutionAttemptV1,
    ExecutionMode,
    ExecutorName,
    Locality,
    MemoryContextItemV1,
    NormalizedRequestV1,
    PlanV1,
    PermissionDisposition,
    ProjectResolutionSource,
    ProjectResolutionStatus,
    ProjectResolutionV1,
    RequestSource,
    RetentionPolicyV1,
    RetryPolicyV1,
    RiskLevel,
    RouteDecisionV1,
    RouteFallbackV1,
    RouteName,
    RouteOverride,
    OverrideDisposition,
    TaskStateV1,
    TaskStatus,
    ToolHealthSpecV1,
    ToolSpecV1,
)

__all__ = [
    "CONTRACT_VERSION",
    "ActionKind",
    "ArtifactMetadataV1",
    "AttachmentRefV1",
    "AttachmentKind",
    "AttemptOutcome",
    "AvailabilityStatus",
    "ComplexityLevel",
    "ContextBudgetV1",
    "DecisionStatus",
    "ExecutionAttemptV1",
    "ExecutionMode",
    "ExecutorName",
    "Locality",
    "MemoryContextItemV1",
    "NormalizedRequestV1",
    "PlanV1",
    "PermissionDisposition",
    "ProjectResolutionSource",
    "ProjectResolutionStatus",
    "ProjectResolutionV1",
    "RequestSource",
    "RetentionPolicyV1",
    "RetryPolicyV1",
    "RiskLevel",
    "RouteDecisionV1",
    "RouteFallbackV1",
    "RouteName",
    "RouteOverride",
    "OverrideDisposition",
    "TaskStateV1",
    "TaskStatus",
    "ToolHealthSpecV1",
    "ToolSpecV1",
]
